// lib/larvae-survey.ts
//
// Larvae Survey Game — survey-board game built from real larva responses.
//
// Boards are PRE-GENERATED by the build route and cached in Redis, so gameplay
// is instant. Generating one board = N in-character responses (one Haiku call
// per larva, run with limited concurrency) + one clustering call that groups
// those responses into ranked board answers.
//
// Guess matching is two-tier: a free normalized/substring pass first, then a
// single Haiku call only when that misses. Obvious hits cost nothing.
//
// Imports only redis + haiku + getIndex + getProfile from lib/larvae.ts —
// nothing in the existing codebase is modified.

import { redis, haiku, getIndex, getProfile } from "@/lib/larvae";

// ─── Types ─────────────────────────────────────────────────────────

/** One clustered answer on the board. */
export type BoardAnswer = {
  rank: number; // 1 = most common
  label: string; // short board text, e.g. "VAGUE ROADMAPS"
  count: number; // how many larvae gave this answer
  points: number; // count, used directly as score
  /** Names of the larvae whose responses landed in this cluster. */
  voices: string[];
  /** One representative quote, for the reveal. */
  sample: string;
  /** One sentence on why the hive clustered here. */
  rationale: string;
  /** Up to two larva quotes for the "least picked" spotlight. */
  quotes: { name: string; answer: string }[];
};

/** A complete playable board. */
export type SurveyBoard = {
  id: string;
  question: string;
  answers: BoardAnswer[];
  respondents: number; // how many larvae were surveyed
  totalPoints: number;
  builtAt: string;
};

/** Raw survey response before clustering. */
type SurveyResponse = {
  wallet: string;
  name: string;
  answer: string;
};

// ─── Question set ──────────────────────────────────────────────────
//
// Seed list is the starting bank. Runtime questions live in Redis so minting
// can grow the pool without a deploy. Build always reads the bank.

export type SurveyQuestion = {
  id: string;
  text: string;
  source: "seed" | "minted";
  createdAt: string;
};

export const SURVEY_QUESTIONS: { id: string; text: string }[] = [
  // All creative / personality bait — analogies, vibes, pop culture.
  // Avoid dry "utility" prompts where every larva says audit/roadmap.
  { id: "q01", text: "If CLAWD's story was a popular movie, which movie would it be?" },
  { id: "q02", text: "Name the animal a larva would reincarnate as." },
  { id: "q03", text: "Name a TV show that describes the hive's group chat." },
  { id: "q04", text: "Name the karaoke song the hive always ruins." },
  { id: "q05", text: "Name a board game that feels like shipping on-chain." },
  { id: "q06", text: "Name the sitcom character that would thrive in the hive." },
  { id: "q07", text: "Name something a larva would put on a dating profile." },
  { id: "q08", text: "Name the emoji that starts a fight in the hive (say the common name, like clown or rocket)." },
  { id: "q09", text: "Name a childhood toy that explains crypto culture." },
  { id: "q10", text: "Name the food that best describes governance drama." },
  { id: "q11", text: "Name a superhero a larva secretly thinks it is." },
  { id: "q12", text: "Name something you'd hear in a larva's nightmare." },
  { id: "q13", text: "If the hive was a reality show, which show would it be?" },
  { id: "q14", text: "Name the snack a larva rage-buys after a bad proposal." },
  { id: "q15", text: "Name a Disney villain that belongs in Discord moderation." },
  { id: "q16", text: "Name the Olympic sport that feels like waiting for a mint." },
  { id: "q17", text: "Name a fashion accessory a larva would never take off." },
  { id: "q18", text: "Name the conspiracy theory larvae whisper at 3am." },
  { id: "q19", text: "Name a video game boss that feels like a token unlock." },
  { id: "q20", text: "Name the houseplant that matches hive politics." },
  { id: "q21", text: "Name a weather forecast for the hive's mood this week." },
  { id: "q22", text: "Name the fictional job title a larva puts on LinkedIn." },
  { id: "q23", text: "Name a magic spell that would fix every roadmap." },
  { id: "q24", text: "Name the last thing a larva would say before rage-quitting." },
  { id: "q25", text: "Name the karaoke hangover the hive regrets most." },
  { id: "q26", text: "If wallet security was airport security, what gets confiscated?" },
  { id: "q27", text: "Name the cooking show a larva would host." },
  { id: "q28", text: "Name the RPG class every larva pretends to main." },
  { id: "q29", text: "Name the museum exhibit that explains the hive." },
  { id: "q30", text: "Name a fairy tale that matches a typical proposal thread." },
  { id: "q31", text: "Name the gym machine a larva uses to cope with FUD." },
  { id: "q32", text: "If the hive was a breakfast cereal, which one would it be?" },
  { id: "q33", text: "Name the group chat nickname nobody asked for but everyone uses." },
  { id: "q34", text: "Name a haunted house attraction based on Discord drama." },
  { id: "q35", text: "Name the playlist a larva queues while waiting for quorum." },
  { id: "q36", text: "Name the escape room theme that feels like claiming rewards." },
]

/** Soft cap so weekly minting doesn't grow forever. */
export const MAX_SURVEY_QUESTIONS = 60;

const QUESTIONS_KEY = "lpp:survey:questions";
const MAX_BOARD_ANSWERS = 8;
/** Ideal playable pool — fill the seed bank so daily packs stay fresh. */
export const TARGET_BOARD_COUNT = 36;

/** Daily Wordle-style session: 3 main rounds + up to 5 Swarm Rush boards. */
export const DAILY_MAIN_ROUNDS = 3;
export const DAILY_FM_QUESTIONS = 5;
export const DAILY_BOARD_NEED = DAILY_MAIN_ROUNDS + DAILY_FM_QUESTIONS;

function seedAsQuestions(): SurveyQuestion[] {
  const stamp = "2026-01-01";
  return SURVEY_QUESTIONS.map((q) => ({
    id: q.id,
    text: q.text,
    source: "seed" as const,
    createdAt: stamp,
  }));
}

async function loadQuestionBankRaw(): Promise<SurveyQuestion[]> {
  const raw = await redis.get<string | SurveyQuestion[]>(QUESTIONS_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

async function saveQuestionBank(questions: SurveyQuestion[]) {
  await redis.set(QUESTIONS_KEY, JSON.stringify(questions));
}

/** Wipe Redis questions and reseed from SURVEY_QUESTIONS (drops minted too). */
export async function resetQuestionBankFromSeed(): Promise<SurveyQuestion[]> {
  await redis.del(QUESTIONS_KEY);
  const seeded = seedAsQuestions();
  await saveQuestionBank(seeded);
  return seeded;
}

/**
 * Ensure Redis has at least the seed questions. Safe to call often.
 * New seed entries are merged in; seed TEXT updates from code overwrite old seed copy.
 */
export async function ensureQuestionBank(): Promise<SurveyQuestion[]> {
  const bank = await loadQuestionBankRaw();
  const byId = new Map(bank.map((q) => [q.id, q]));
  let changed = bank.length === 0;

  for (const s of seedAsQuestions()) {
    const existing = byId.get(s.id);
    if (!existing) {
      byId.set(s.id, s);
      changed = true;
      continue;
    }
    // Keep minted questions; refresh seed wording when the code list changes.
    if (existing.source === "seed" && existing.text !== s.text) {
      byId.set(s.id, { ...existing, text: s.text });
      changed = true;
    }
  }

  const merged = Array.from(byId.values()).sort((a, b) => a.id.localeCompare(b.id));
  if (changed) await saveQuestionBank(merged);
  return merged;
}

export async function getQuestionBank(): Promise<SurveyQuestion[]> {
  return ensureQuestionBank();
}

export async function getQuestion(id: string): Promise<SurveyQuestion | null> {
  const bank = await getQuestionBank();
  return bank.find((q) => q.id === id) || null;
}

function nextQuestionIds(bank: SurveyQuestion[], count: number): string[] {
  let max = 0;
  for (const q of bank) {
    const m = /^q(\d+)$/i.exec(q.id);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  const ids: string[] = [];
  for (let i = 1; i <= count; i++) {
    ids.push(`q${String(max + i).padStart(2, "0")}`);
  }
  return ids;
}

function normQuestion(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tooSimilar(a: string, b: string): boolean {
  const wa = new Set(normQuestion(a).split(" ").filter((w) => w.length > 2));
  const wb = new Set(normQuestion(b).split(" ").filter((w) => w.length > 2));
  if (wa.size === 0 || wb.size === 0) return normQuestion(a) === normQuestion(b);
  let overlap = 0;
  for (const w of wa) if (wb.has(w)) overlap++;
  const ratio = overlap / Math.min(wa.size, wb.size);
  return ratio >= 0.7 || normQuestion(a) === normQuestion(b);
}

const MINT_SYSTEM = `You invent survey questions for a knockoff game-show survey about larvae — personal AI agents in the CLAWD / crypto-build hive.

Goal: questions that different larvae will answer DIFFERENTLY, with personality — not dry "utility" prompts where everyone says audit / roadmap / transparency.

Prefer creative formats:
- Analogies: "If CLAWD's story was a movie, which movie…", "Name the animal a larva would reincarnate as."
- Pop culture / vibes: TV shows, songs, board games, sitcom characters, emojis, food metaphors, nightmares, dating-profile bits.
- Social / hive drama that still invites weird answers.

Avoid:
- Generic governance checklists (audits, roadmaps, KPIs) as the obvious only answer.
- Near-duplicates of the existing list.
- Yes/no or one-correct-answer trivia.

Rules:
- One sentence each, under 110 characters.
- May start with Name / If / What / Which / Who.
- Return ONLY a JSON array of strings, no markdown, no preamble.
Example: ["If the hive was a reality show, which show would it be?","Name the snack a larva rage-buys after a bad proposal."]`;

/**
 * Mint up to `count` new questions into the Redis bank.
 * Dedupes against the existing bank. No-ops if already at MAX_SURVEY_QUESTIONS.
 */
export async function mintQuestions(count = 3): Promise<{
  minted: SurveyQuestion[];
  bankSize: number;
  skippedReason?: string;
}> {
  const bank = await getQuestionBank();
  const room = MAX_SURVEY_QUESTIONS - bank.length;
  if (room <= 0) {
    return { minted: [], bankSize: bank.length, skippedReason: "at cap" };
  }
  const want = Math.min(count, room);

  const existingList = bank.map((q) => `- ${q.text}`).join("\n");
  const raw = await haiku(
    MINT_SYSTEM,
    `Existing questions (do not duplicate):\n${existingList}\n\nInvent ${want} NEW questions.`,
    500
  );

  let parsed: unknown;
  try {
    const clean = raw.replace(/```json|```/g, "").trim();
    const start = clean.indexOf("[");
    const end = clean.lastIndexOf("]");
    parsed = JSON.parse(clean.slice(start, end + 1));
  } catch {
    return { minted: [], bankSize: bank.length, skippedReason: "parse failed" };
  }

  if (!Array.isArray(parsed)) {
    return { minted: [], bankSize: bank.length, skippedReason: "not an array" };
  }

  const candidates = parsed
    .map((t) => String(t || "").trim())
    .filter((t) => t.length >= 12 && t.length <= 140)
    .filter((t) => /^(name|if |what |which |who |where )/i.test(t));

  const accepted: string[] = [];
  for (const text of candidates) {
    if (accepted.length >= want) break;
    const clash =
      bank.some((q) => tooSimilar(q.text, text)) ||
      accepted.some((a) => tooSimilar(a, text));
    if (!clash) {
      accepted.push(text.replace(/\s+/g, " ").trim());
    }
  }

  if (accepted.length === 0) {
    return { minted: [], bankSize: bank.length, skippedReason: "all duplicates" };
  }

  const ids = nextQuestionIds(bank, accepted.length);
  const minted: SurveyQuestion[] = accepted.map((text, i) => ({
    id: ids[i],
    text,
    source: "minted" as const,
    createdAt: new Date().toISOString().slice(0, 10),
  }));

  const next = [...bank, ...minted].sort((a, b) => a.id.localeCompare(b.id));
  await saveQuestionBank(next);
  return { minted, bankSize: next.length };
}

// ─── Redis keys ────────────────────────────────────────────────────

const BOARD_KEY = (id: string) => `lpp:survey:board:${id}`;
const BOARD_INDEX_KEY = "lpp:survey:index";
const BUILD_QUEUE_KEY = "lpp:survey:queue";
const MATCH_COUNT_KEY = (day: string) => `lpp:survey:matches:${day}`;
const DAILY_PACK_KEY = (day: string) => `lpp:survey:daily:${day}`;
const DAILY_PLAYED_KEY = (day: string, playerId: string) =>
  `lpp:survey:daily-played:${day}:${playerId}`;
/** Board ids already used in a daily pack, oldest first (LRU recycle). */
const DAILY_USED_KEY = "lpp:survey:daily-used";

export type DailyPack = {
  day: string;
  mainIds: string[];
  fmIds: string[];
  createdAt: string;
};

/** UTC calendar day — shared global puzzle like a hive Wordle. */
export function surveyUtcDay(d = new Date()): string {
  return d.toISOString().slice(0, 10);
}

function surveyUtcDayOffset(day: string, offsetDays: number): string {
  const [y, m, d] = day.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d + offsetDays)).toISOString().slice(0, 10);
}

export function nextUtcMidnightMs(from = new Date()): number {
  return Date.UTC(from.getUTCFullYear(), from.getUTCMonth(), from.getUTCDate() + 1);
}

function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Deterministic shuffle so everyone gets the same daily pack. */
function seededShuffle(ids: string[], seed: string): string[] {
  const a = [...ids];
  let h = hashSeed(seed);
  for (let i = a.length - 1; i > 0; i--) {
    h = (Math.imul(h, 1664525) + 1013904223) >>> 0;
    const j = h % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const THEME_STOP = new Set([
  "name", "the", "that", "this", "which", "would", "could", "hive", "larva",
  "larvae", "something", "someone", "always", "never", "best", "feels", "like",
  "with", "from", "your", "their", "about", "after", "before", "every", "secret",
  "popular", "typical", "describe", "describes", "matches", "belong", "belongs",
]);

/** True when two questions share a distinctive theme word (karaoke/karaoke). */
function sameTheme(a: string, b: string): boolean {
  if (tooSimilar(a, b)) return true;
  const sig = (s: string) =>
    new Set(
      normQuestion(s)
        .split(" ")
        .filter((w) => w.length >= 5 && !THEME_STOP.has(w))
    );
  const sa = sig(a);
  const sb = sig(b);
  for (const w of sa) if (sb.has(w)) return true;
  return false;
}

export async function getDailyUsedIds(): Promise<string[]> {
  const raw = await redis.get<string | string[]>(DAILY_USED_KEY);
  if (!raw) return [];
  const ids = typeof raw === "string" ? JSON.parse(raw) : raw;
  return Array.isArray(ids) ? ids.map(String).filter(Boolean) : [];
}

async function recordDailyUsed(ids: string[]) {
  if (ids.length === 0) return;
  const prev = await getDailyUsedIds();
  const picked = new Set(ids);
  const next = [...prev.filter((id) => !picked.has(id)), ...ids];
  await redis.set(DAILY_USED_KEY, JSON.stringify(next.slice(-240)));
}

/** How many built boards have never appeared in a daily pack. */
export async function unusedBoardCount(): Promise<number> {
  const index = await getBoardIndex();
  const used = new Set(await getDailyUsedIds());
  return index.filter((id) => !used.has(id)).length;
}

/**
 * Prefer never-used boards, then oldest-used. Skip same-theme questions
 * in one pack so you don't get two karaoke rounds in a day.
 */
function pickDailyBoardIds(
  index: string[],
  used: string[],
  textById: Map<string, string>,
  seed: string,
  n: number
): string[] {
  const usedSet = new Set(used);
  const never = seededShuffle(
    index.filter((id) => !usedSet.has(id)),
    `${seed}-fresh`
  );
  const lru = used.filter((id) => index.includes(id));
  const pool = [...never, ...lru.filter((id) => !never.includes(id))];

  const picked: string[] = [];
  const clashes = (id: string) => {
    const t = textById.get(id) || "";
    if (!t) return false;
    return picked.some((p) => sameTheme(textById.get(p) || "", t));
  };
  for (const id of pool) {
    if (picked.length >= n) break;
    if (!picked.includes(id) && !clashes(id)) picked.push(id);
  }
  for (const id of pool) {
    if (picked.length >= n) break;
    if (!picked.includes(id)) picked.push(id);
  }
  return picked.slice(0, n);
}

function dailyTtlSeconds(day: string): number {
  // Live until end of that UTC day + 24h buffer, then vanish.
  const [y, m, d] = day.split("-").map(Number);
  const end = Date.UTC(y, m - 1, d + 2); // midnight after next day
  return Math.max(3600, Math.ceil((end - Date.now()) / 1000));
}

export async function getDailyPack(day = surveyUtcDay()): Promise<DailyPack | null> {
  const raw = await redis.get<string | DailyPack>(DAILY_PACK_KEY(day));
  if (!raw) return null;
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

/**
 * Create or return today's fixed pack (3 main + up to 5 FM).
 * Same day + same pool → same boards for everyone.
 * Never re-picks a used board until the unused pool is empty (then LRU).
 */
export async function getOrCreateDailyPack(day = surveyUtcDay()): Promise<DailyPack | null> {
  const existing = await getDailyPack(day);
  if (existing?.mainIds?.length) {
    const ids = [...existing.mainIds, ...(existing.fmIds || [])];
    const used = await getDailyUsedIds();
    if (!ids.every((id) => used.includes(id))) await recordDailyUsed(ids);
    return existing;
  }

  const index = await getBoardIndex();
  if (index.length < DAILY_MAIN_ROUNDS) return null;

  const need = Math.min(DAILY_BOARD_NEED, index.length);
  const [used, bank, yesterday] = await Promise.all([
    getDailyUsedIds(),
    getQuestionBank(),
    getDailyPack(surveyUtcDayOffset(day, -1)),
  ]);
  const yIds = yesterday ? [...yesterday.mainIds, ...(yesterday.fmIds || [])] : [];
  const usedForPick = [...used];
  for (const id of yIds) if (!usedForPick.includes(id)) usedForPick.push(id);

  const textById = new Map(bank.map((q) => [q.id, q.text]));
  const picked = pickDailyBoardIds(index, usedForPick, textById, `hive-daily-${day}`, need);
  const pack: DailyPack = {
    day,
    mainIds: picked.slice(0, DAILY_MAIN_ROUNDS),
    fmIds: picked.slice(DAILY_MAIN_ROUNDS, need),
    createdAt: new Date().toISOString(),
  };
  await redis.set(DAILY_PACK_KEY(day), JSON.stringify(pack), { ex: dailyTtlSeconds(day) });
  await recordDailyUsed([...yIds, ...picked]);
  return pack;
}

export function isValidSurveyPlayerId(playerId: string): boolean {
  return /^[a-zA-Z0-9_-]{8,64}$/.test(playerId);
}

export async function hasPlayedDaily(day: string, playerId: string): Promise<boolean> {
  if (!isValidSurveyPlayerId(playerId)) return false;
  const v = await redis.get(DAILY_PLAYED_KEY(day, playerId));
  return Boolean(v);
}

/** Claim today's one play. Fails if already claimed. */
export async function claimDailyPlay(
  day: string,
  playerId: string
): Promise<{ ok: boolean; reason?: string }> {
  if (!isValidSurveyPlayerId(playerId)) return { ok: false, reason: "bad player id" };
  if (day !== surveyUtcDay()) return { ok: false, reason: "not today's puzzle" };

  const key = DAILY_PLAYED_KEY(day, playerId);
  const ttl = dailyTtlSeconds(day);
  // Upstash returns "OK" on success, null when NX misses (already set).
  const res = await redis.set(key, new Date().toISOString(), { nx: true, ex: ttl });
  if (res === "OK") return { ok: true };
  if (await redis.get(key)) return { ok: false, reason: "already played today" };
  // Rare race: write without nx
  await redis.set(key, new Date().toISOString(), { ex: ttl });
  return { ok: true };
}

// ─── Redis ops ─────────────────────────────────────────────────────

export async function saveBoard(board: SurveyBoard) {
  await redis.set(BOARD_KEY(board.id), JSON.stringify(board));
  const index = await getBoardIndex();
  if (!index.includes(board.id)) {
    await redis.set(BOARD_INDEX_KEY, JSON.stringify([...index, board.id]));
  }
}

/** Decorative fluff + state modifiers models bolt onto the same answer. */
const LABEL_ARTICLES = new Set(["a", "an", "the", "my", "our", "some", "any"]);
const LABEL_DECORATIVE = new Set([
  "fierce", "chaotic", "crazy", "wild", "sassy", "spicy", "cursed", "based",
  "epic", "legendary", "ultimate", "absolute", "total", "giant", "tiny",
  "little", "big", "angry", "sleepy", "feral", "deranged", "holy", "lowkey",
  "literally", "basically", "probably", "definitely", "obviously", "kinda",
  "super", "mega", "ultra", "random", "weird", "goofy", "silly", "smug",
  // state / quality padding that creates fake duplicate board rows
  "overcooked", "undercooked", "uncooked", "overripe", "underripe", "raw",
  "burnt", "burned", "cold", "hot", "broken", "failed", "failing", "collapsing",
  "collapse", "collapsed", "decay", "decaying", "rotting", "rotten", "variant",
  "versions", "version", "style", "vibes", "energy", "core", "mode",
  // verb/state pads bolted onto animals / nouns ("salmon upstream")
  "upstream", "downstream", "swimming", "flying", "crawling", "running",
  "jumping", "diving", "lurking", "hiding", "sleeping", "working",
  // job / metaphor pads ("accountant ant")
  "accountant", "lawyer", "banker", "ceo", "intern", "manager", "consultant",
  "engineer", "artist", "poet", "warrior", "soldier", "ninja", "wizard",
]);
const LABEL_FILLER = new Set([...LABEL_ARTICLES, ...LABEL_DECORATIVE]);

function foldText(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function contentTokens(label: string): string[] {
  return foldText(label)
    .split(" ")
    .filter((w) => w.length > 1 && !LABEL_FILLER.has(w));
}

function labelCore(label: string): string {
  return contentTokens(label).join(" ");
}

/** True when two board labels are the same idea with different padding. */
function sameAnswerFamily(a: string, b: string): boolean {
  const ta = contentTokens(a);
  const tb = contentTokens(b);
  if (ta.length === 0 || tb.length === 0) return false;
  const ca = ta.join(" ");
  const cb = tb.join(" ");
  if (ca === cb) return true;
  if (ca.includes(cb) || cb.includes(ca)) return true;
  const [short, long] = ta.length <= tb.length ? [ta, tb] : [tb, ta];
  if (short.every((t) => long.includes(t))) return true;
  // Shared distinctive noun (e.g. all the SOUFFLÉ / OVERCOOKED SOUFFLÉ rows)
  const nouns = (toks: string[]) => toks.filter((t) => t.length >= 4);
  const na = nouns(ta);
  const nb = nouns(tb);
  return na.some((n) => nb.includes(n));
}

/** Board label: drop decorative/state fluff, keep the plain noun/title. */
function plainLabel(label: string): string {
  const folded = foldText(label);
  let words = folded.split(" ").filter(Boolean);
  // Drop trailing redundant type words ("remora fish" → "remora")
  if (words.length >= 2) {
    const last = words[words.length - 1];
    if (["fish", "bird", "bug", "insect", "animal", "creature"].includes(last)) {
      words = words.slice(0, -1);
    }
  }
  const kept = words.filter((w) => !LABEL_DECORATIVE.has(w));
  return (kept.length > 0 ? kept : words).join(" ").toUpperCase().slice(0, 40);
}

/** Template/echo/generic rationales that aren't real "thinking" copy. */
function isWeakRationale(
  rationale: string,
  label: string,
  sample?: string
): boolean {
  const r = (rationale || "").trim();
  if (!r) return true;
  if (/landed here/i.test(r)) return true;
  if (/put it plainly/i.test(r)) return true;
  if (/lone larva took this swing/i.test(r)) return true;
  if (/fringe call from the hive/i.test(r)) return true;
  if (/smaller pocket of the hive/i.test(r)) return true;
  if (/only \d+ larva/i.test(r) && /went (here|this way)/i.test(r)) return true;
  const echo = foldText(sample || label);
  if (echo && foldText(r) === echo) return true;
  // "… — e.g. \"Mr. Brightside\"." style
  if (/\be\.g\.\s*["']/i.test(r)) return true;
  return false;
}

/** @deprecated alias — prefer isWeakRationale */
function isTemplateRationale(
  rationale: string,
  label: string,
  sample?: string
): boolean {
  return isWeakRationale(rationale, label, sample);
}

function fallbackRationale(a: { count: number; label: string }): string {
  const n = a.count;
  if (n <= 1) return "A lone larva took this swing — rare enough to spotlight.";
  if (n <= 3) return `Only ${n} larvae went this way — a fringe call from the hive.`;
  return `A smaller pocket of the hive (${n}) clustered here.`;
}

/** True when a quote is just the board label restated. */
function quoteEchoesLabel(answer: string, label: string): boolean {
  const a = foldText(answer);
  const l = foldText(label);
  if (!a || !l) return true;
  if (a === l) return true;
  if (sameAnswerFamily(a, l) && Math.abs(a.length - l.length) <= 12) return true;
  return false;
}

/** Prefer two distinct answer phrasings that aren't just the board label. */
function pickQuotes(
  members: { name: string; answer: string }[],
  label = ""
): { name: string; answer: string }[] {
  if (members.length === 0) return [];
  const out: { name: string; answer: string }[] = [];
  const seenAnswers = new Set<string>();
  const seenNames = new Set<string>();

  const tryPush = (m: { name: string; answer: string }, requireDistinct: boolean) => {
    if (out.length >= 2) return;
    const key = foldText(m.answer);
    if (!key || seenAnswers.has(key)) return;
    if (requireDistinct && label && quoteEchoesLabel(m.answer, label)) return;
    seenAnswers.add(key);
    seenNames.add(m.name);
    out.push({ name: m.name, answer: m.answer.slice(0, 80) });
  };

  // Pass 1: distinct wording vs the board label
  for (const m of members) tryPush(m, true);
  // Pass 2: any unused voice with distinct answer text
  for (const m of members) {
    if (out.length >= 2) break;
    if (seenNames.has(m.name)) continue;
    tryPush(m, true);
  }
  // Never invent a quote that just repeats the label — UI will name-drop instead.
  return out;
}

function quotesFromLegacy(a: {
  voices?: string[];
  sample?: string;
  label?: string;
  quotes?: { name: string; answer: string }[];
}): { name: string; answer: string }[] {
  const label = a.label || "";
  if (Array.isArray(a.quotes) && a.quotes.length > 0) {
    return a.quotes
      .filter((q) => q?.name && q?.answer && !quoteEchoesLabel(String(q.answer), label))
      .slice(0, 2)
      .map((q) => ({ name: String(q.name), answer: String(q.answer).slice(0, 80) }));
  }
  // Old boards only have sample === label — don't fabricate fake quote cards.
  return [];
}

/**
 * Fix already-cached boards without a rebuild: strip decorative adjectives,
 * merge near-duplicate rows, backfill rationale.
 */
function sanitizeBoard(board: SurveyBoard): { board: SurveyBoard; changed: boolean } {
  const raw = board.answers || [];
  const merged: BoardAnswer[] = [];

  for (const a of raw) {
    const label = plainLabel(a.label || "");
    if (!label) continue;
    const rawRationale = (a.rationale || "").trim();
    const next: BoardAnswer = {
      rank: a.rank,
      label,
      count: a.count,
      points: a.points ?? a.count,
      voices: [...(a.voices || [])],
      sample: a.sample || label,
      rationale: isTemplateRationale(rawRationale, label, a.sample)
        ? fallbackRationale({ count: a.count, label })
        : rawRationale,
      quotes: quotesFromLegacy({ ...a, label }),
    };
    const hit = merged.find((o) => sameAnswerFamily(o.label, next.label));
    if (!hit) {
      merged.push(next);
      continue;
    }
    hit.count += next.count;
    hit.points += next.points;
    hit.voices.push(...next.voices);
    // Prefer the shortest plain label (SOUFFLÉ beats OVERCOOKED SOUFFLÉ)
    if (next.label.replace(/\s+/g, "").length < hit.label.replace(/\s+/g, "").length) {
      hit.label = next.label;
    }
    if (!hit.sample || next.sample.length < hit.sample.length) hit.sample = next.sample;
    if (next.rationale.length > hit.rationale.length) hit.rationale = next.rationale;
    // Keep up to two quotes after merge, preferring distinct answers.
    hit.quotes = pickQuotes(
      [
        ...hit.quotes.map((q) => ({ name: q.name, answer: q.answer })),
        ...next.quotes.map((q) => ({ name: q.name, answer: q.answer })),
      ],
      hit.label
    );
    if (isTemplateRationale(hit.rationale, hit.label, hit.sample)) {
      hit.rationale = fallbackRationale({ count: hit.count, label: hit.label });
    }
  }

  const ranked = merged
    .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label))
    .slice(0, MAX_BOARD_ANSWERS)
    .map((a, i) => ({ ...a, rank: i + 1, points: a.count }));

  const totalPoints = ranked.reduce((s, a) => s + a.points, 0);
  const changed =
    ranked.length !== raw.length ||
    totalPoints !== board.totalPoints ||
    ranked.some((a, i) => {
      const b = raw[i];
      return (
        !b ||
        a.label !== plainLabel(b.label || "") ||
        a.count !== b.count ||
        a.rationale !== (b.rationale || "").trim() ||
        JSON.stringify(a.quotes || []) !== JSON.stringify(b.quotes || []) ||
        isTemplateRationale(b.rationale || "", a.label, b.sample)
      );
    });

  return {
    board: { ...board, answers: ranked, totalPoints },
    changed,
  };
}

export async function getBoard(id: string): Promise<SurveyBoard | null> {
  const raw = await redis.get<string | SurveyBoard>(BOARD_KEY(id));
  if (!raw) return null;
  const board: SurveyBoard = typeof raw === "string" ? JSON.parse(raw) : raw;
  const { board: cleaned, changed } = sanitizeBoard(board);
  if (changed) {
    // Persist cleaned labels / merged dupes so players never need a manual rebuild.
    await saveBoard(cleaned);
  }
  return cleaned;
}

/**
 * Least-picked spotlight needs a real "what they were thinking" line.
 * Survey answers are often 1–4 words that match the board label, so we can't
 * quote them usefully — generate a grounded rationale (+ optional asides)
 * once on reveal and cache it on the board.
 */
export async function enrichLeastPicked(board: SurveyBoard): Promise<SurveyBoard> {
  const answers = [...(board.answers || [])];
  if (answers.length === 0) return board;

  const lastIdx = answers.reduce(
    (best, a, i) => (a.rank > answers[best].rank ? i : best),
    0
  );
  const last = answers[lastIdx];
  const needWhy = isWeakRationale(last.rationale, last.label, last.sample);
  const existingQuotes = (last.quotes || []).filter(
    (q) => q?.name && q?.answer && !quoteEchoesLabel(q.answer, last.label)
  );
  const maxQuotes = Math.min(2, Math.max(1, last.count || 1));
  const needQuotes = existingQuotes.length === 0;

  if (!needWhy && !needQuotes) return board;

  const voices = (last.voices || []).filter(Boolean).slice(0, maxQuotes);
  const voiceLine =
    voices.length > 0 ? voices.join(", ") : "a couple of fringe larvae";

  try {
    const raw = await haiku(
      `You write the "least picked" reveal for a hive survey game.
Return ONLY JSON (no markdown): {"rationale":"...","quotes":[{"name":"...","answer":"..."}]}

Rules:
- rationale: ONE punchy sentence on WHY this answer is a funny/fitting fringe pick for the question. Never restate the label alone. Never say "landed here", "e.g.", "smaller pocket", "fringe call", or "lone larva took this swing".
- quotes: up to ${maxQuotes} short first-person asides (max 14 words) from the named larvae — their vibe for picking this, NOT just repeating the answer word. Use the provided names only.
- If only one name is given, return one quote.
- Keep it playful, specific to the question + answer.`,
      `Question: ${board.question}
Answer on the board: ${last.label}
Sample phrasing: ${last.sample || last.label}
How many larvae: ${last.count}
Larva names to use: ${voiceLine}`,
      280,
      0.85
    );

    const clean = raw.replace(/```json|```/g, "").trim();
    const start = clean.indexOf("{");
    const end = clean.lastIndexOf("}");
    if (start === -1 || end === -1) return board;

    const parsed = JSON.parse(clean.slice(start, end + 1)) as {
      rationale?: string;
      quotes?: { name?: string; answer?: string }[];
    };

    let rationale = String(parsed.rationale || "")
      .trim()
      .replace(/\s+/g, " ")
      .slice(0, 200);
    if (!rationale || isWeakRationale(rationale, last.label, last.sample)) {
      rationale = last.rationale; // keep prior if model failed
    } else if (needWhy) {
      last.rationale = rationale;
    }

    if (needQuotes && Array.isArray(parsed.quotes)) {
      const allowed = new Set(voices.map((v) => v.toLowerCase()));
      const quotes = parsed.quotes
        .filter((q) => q?.name && q?.answer)
        .map((q) => ({
          name: String(q.name).trim(),
          answer: String(q.answer).trim().slice(0, 80),
        }))
        .filter((q) => {
          if (allowed.size > 0 && !allowed.has(q.name.toLowerCase())) return false;
          // Reject asides that are just the board label again
          return !quoteEchoesLabel(q.answer, last.label);
        })
        .slice(0, maxQuotes);
      if (quotes.length > 0) last.quotes = quotes;
    }

    answers[lastIdx] = last;
    const next = { ...board, answers };
    await saveBoard(next);
    return next;
  } catch {
    return board;
  }
}

export async function getBoardIndex(): Promise<string[]> {
  const raw = await redis.get<string | string[]>(BOARD_INDEX_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export async function getAllBoards(): Promise<SurveyBoard[]> {
  const index = await getBoardIndex();
  const boards = await Promise.all(index.map((id) => getBoard(id)));
  return boards.filter(Boolean) as SurveyBoard[];
}

export async function getBuildQueue(): Promise<string[]> {
  const raw = await redis.get<string | string[]>(BUILD_QUEUE_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export async function setBuildQueue(ids: string[]) {
  await redis.set(BUILD_QUEUE_KEY, JSON.stringify(ids));
}

export async function clearBuildQueue() {
  await redis.del(BUILD_QUEUE_KEY);
}

export async function clearAllBoards() {
  const index = await getBoardIndex();
  for (const id of index) await redis.del(BOARD_KEY(id));
  await redis.del(BOARD_INDEX_KEY);
  await redis.del(BUILD_QUEUE_KEY);
  await redis.del(DAILY_USED_KEY);
}

const ENSURE_LOCK_KEY = "lpp:survey:ensure-lock";

/**
 * Public-safe progress tick: build missing boards toward TARGET_BOARD_COUNT.
 * No wipe, no secret. Rate-limited so page polls can't stampede Redis/LLM.
 * Safe to call from the play page — advances one chunk per call.
 */
export async function tickMissingBoardBuild(
  budgetMs = 45_000
): Promise<{
  builtThisRun: { id: string; answers: number; respondents: number }[];
  remaining: number;
  brewing: boolean;
  skipped?: string;
}> {
  const lock = await redis.set(ENSURE_LOCK_KEY, "1", { nx: true, ex: 90 });
  if (lock !== "OK") {
    const existing = await getBoardIndex();
    const queue = await getBuildQueue();
    return {
      builtThisRun: [],
      remaining: queue.length,
      brewing: existing.length < TARGET_BOARD_COUNT || queue.length > 0,
      skipped: "busy",
    };
  }

  try {
    await ensureQuestionBank();
    const start = Date.now();
    let queue = await getBuildQueue();
    const existing = await getBoardIndex();
    const bank = await getQuestionBank();

    if (queue.length === 0) {
      const missing = bank
        .filter((q) => !existing.includes(q.id))
        .map((q) => q.id)
        .slice(0, Math.max(0, TARGET_BOARD_COUNT - existing.length));
      if (missing.length === 0) {
        return {
          builtThisRun: [],
          remaining: 0,
          brewing: false,
          skipped: "full",
        };
      }
      queue = missing;
      await setBuildQueue(queue);
    }

    const builtThisRun: { id: string; answers: number; respondents: number }[] = [];

    while (queue.length > 0 && Date.now() - start < budgetMs) {
      const id = queue.shift()!;
      try {
        const board = await buildBoard(id);
        if (board) {
          await saveBoard(board);
          builtThisRun.push({
            id: board.id,
            answers: board.answers.length,
            respondents: board.respondents,
          });
        }
      } catch {
        // leave failed id out of queue — don't spin forever
      }
      await setBuildQueue(queue);
      // One board per tick is enough for public ensure; keep latency predictable.
      if (builtThisRun.length >= 1) break;
    }

    if (queue.length === 0) await clearBuildQueue();
    const finalIndex = await getBoardIndex();
    return {
      builtThisRun,
      remaining: queue.length,
      brewing: finalIndex.length < TARGET_BOARD_COUNT || queue.length > 0,
    };
  } finally {
    await redis.del(ENSURE_LOCK_KEY);
  }
}

// ─── Respondent selection ──────────────────────────────────────────

/**
 * Pick which larvae answer a given question.
 *
 * Deliberately NOT "top N by response count" — that makes every board the same
 * five voices. Instead: seed a rotating window from the question id so each
 * question surveys a different slice of the hive, while staying deterministic
 * (rebuilding the same board twice gives the same respondents).
 */
function pickRespondents(
  index: { wallet: string; responseCount: number }[],
  questionId: string,
  count: number
): { wallet: string }[] {
  if (index.length === 0) return [];

  // Only consider larvae with enough history to have a real personality.
  const eligible = index.filter((e) => e.responseCount >= 3);
  const pool = eligible.length >= count ? eligible : index;

  let seed = 0;
  for (const c of questionId) seed = (seed * 31 + c.charCodeAt(0)) >>> 0;

  const start = seed % pool.length;
  const picked: { wallet: string }[] = [];
  const stride = 1 + (seed % 3); // vary the stride so windows overlap differently

  for (let i = 0; i < Math.min(count, pool.length); i++) {
    const idx = (start + i * stride) % pool.length;
    const entry = pool[idx];
    if (!picked.some((p) => p.wallet === entry.wallet)) {
      picked.push({ wallet: entry.wallet });
    }
  }

  // Stride may collide on small pools — top up sequentially if short.
  if (picked.length < Math.min(count, pool.length)) {
    for (const entry of pool) {
      if (picked.length >= count) break;
      if (!picked.some((p) => p.wallet === entry.wallet)) {
        picked.push({ wallet: entry.wallet });
      }
    }
  }

  return picked;
}

// ─── Survey phase ──────────────────────────────────────────────────

type AnswerCategory =
  | "emoji"
  | "food"
  | "animal"
  | "movie"
  | "tv"
  | "song"
  | "game"
  | "character"
  | "toy"
  | "person"
  | "thing";

/** Infer what kind of answer the question is asking for. */
export function inferAnswerCategory(question: string): AnswerCategory {
  const q = question.toLowerCase();
  if (/\bemoji/.test(q)) return "emoji";
  if (/\b(food|snack|cereal|breakfast|cooking|souffl)/.test(q)) return "food";
  if (/\banimal|reincarnat|creature|pet\b/.test(q)) return "animal";
  if (/\bmovie|film\b/.test(q)) return "movie";
  if (/\b(tv show|sitcom|reality show|series)\b/.test(q)) return "tv";
  if (/\b(song|karaoke|playlist)\b/.test(q)) return "song";
  if (/\b(board game|video game|rpg|olympic sport)\b/.test(q)) return "game";
  if (/\b(character|villain|superhero|boss)\b/.test(q)) return "character";
  if (/\b(toy|lego|tamagotchi)\b/.test(q)) return "toy";
  if (/\b(who|job title|linkedIn)\b/.test(q)) return "person";
  return "thing";
}

function categoryBrief(cat: AnswerCategory): string {
  switch (cat) {
    case "emoji":
      return "Answer with the COMMON ENGLISH NAME of an emoji only (clown, rocket, skull, fire, clown face). Never a sentence. Never a governance rant.";
    case "food":
      return "Answer with a real food / dish / snack name only.";
    case "animal":
      return "Answer with a real animal name only.";
    case "movie":
      return "Answer with a real movie title only.";
    case "tv":
      return "Answer with a real TV show title only.";
    case "song":
      return "Answer with a real song title only.";
    case "game":
      return "Answer with a real game / sport name only.";
    case "character":
      return "Answer with a real fictional character name only.";
    case "toy":
      return "Answer with a real toy / toy brand name only.";
    case "person":
      return "Answer with a person / role / title only.";
    default:
      return "Answer with a short concrete noun phrase that literally answers the question.";
  }
}

const SURVEY_SYSTEM = `You are a larva — a personal AI governance agent in the $CLAWD ecosystem — answering a survey question in character.

Answer with a SHORT phrase: usually 1-3 words (titles and proper nouns are fine). Not a sentence. Not an explanation. Just the answer itself.

Rules:
- Name the thing itself. Do NOT pad with jobs, verbs, or state fluff ("accountant ant", "salmon upstream") — say "ant" / "salmon".
- Your answer MUST match the question's category (see the category line below). Off-category answers are invalid.
- No filler like "definitely", "probably", "obviously", "lowkey", "collapse", "variant", "broken".
- Do NOT answer with abstract crypto jargon (roadmap, audit, tokenomics, receipts) unless the question literally asks for that.

Answer from YOUR personality, not the obvious general answer. Unusual picks are fine — wrong category is not.

Respond with ONLY the phrase, nothing else. No quotes, no punctuation at the end.`;

async function surveyOne(
  wallet: string,
  question: string
): Promise<SurveyResponse | null> {
  const p = await getProfile(wallet);
  if (!p) return null;

  const cat = inferAnswerCategory(question);
  const system = `${SURVEY_SYSTEM}

CATEGORY RULE: ${categoryBrief(cat)}

You are "${p.profile.name}".
Tone: ${p.profile.tone}
Values: ${p.profile.values.join("; ")}
Quirks: ${p.profile.quirks.join("; ")}
About you: ${p.profile.summary}`;

  try {
    const raw = await haiku(system, question, 40);
    const answer = raw
      .trim()
      .replace(/^["'`]+|["'`.,!]+$/g, "")
      .replace(/\s+/g, " ")
      .slice(0, 60);
    if (!answer) return null;
    // Drop decorative adjectives ("fierce honey badger" → "honey badger").
    const words = answer.split(/\s+/);
    const kept = words.filter((w) => !LABEL_DECORATIVE.has(w.toLowerCase()));
    const cleaned = (kept.length > 0 ? kept : words).join(" ").slice(0, 60);
    return { wallet: p.wallet, name: p.profile.name, answer: cleaned };
  } catch {
    return null;
  }
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let i = 0;
  async function worker() {
    while (i < items.length) {
      const idx = i++;
      results[idx] = await fn(items[idx]);
    }
  }
  await Promise.all(new Array(Math.min(limit, items.length)).fill(0).map(worker));
  return results;
}

// ─── Clustering phase ──────────────────────────────────────────────

const CLUSTER_SYSTEM = `You are building a survey board for a "guess what the hive said" game (Family Feud style).

You will receive a question, the REQUIRED answer category, and a numbered list of short answers. Group answers that mean the SAME THING into clusters, even when worded differently.

CRITICAL — category lock:
- Every board label MUST be a valid answer to the question's category.
- DROP answers that are off-category (do not put them on the board). Example: for an emoji question, drop "vague roadmap" / "tokenomics spin". For a food question, drop "governance".
- For emoji questions, labels must be COMMON EMOJI NAMES in UPPERCASE (ROCKET, CLOWN, FIRE, SKULL, TURTLE) — never sentences.

CRITICAL — do NOT leave state/adjective variants as separate rows. These are ONE cluster each:
- "soufflé" + "overcooked soufflé" → SOUFFLÉ
- "honey badger" + "fierce honey badger" → HONEY BADGER
- "lego with no instructions" + "lego mindstorms" → LEGO (same toy family)

Rules:
- Merge aggressively on meaning and on shared head noun.
- Never invent adjectives. Prefer the PLAINEST shared noun/phrase for the label (1-3 words, UPPERCASE).
- For each cluster, write a "rationale": exactly ONE vivid sentence explaining the JOKE / vibe — never restate the label, never say "N larvae landed here", never use "e.g.".
- Return clusters sorted by size, largest first.
- Only include respondent numbers whose answers fit the category. Off-category answers are omitted entirely.
- Prefer 4–8 clusters. If fewer than 3 on-category clusters exist, still return what you have.

Respond with ONLY a JSON array, no markdown, no preamble:
[{"label":"SOUFFLÉ","rationale":"The hive kept describing governance as a soufflé that falls the second you look at it.","members":[1,4,9]}, ...]`;

type Cluster = { label: string; rationale: string; members: number[] };

async function clusterResponses(
  question: string,
  responses: SurveyResponse[]
): Promise<Cluster[]> {
  const cat = inferAnswerCategory(question);
  const numbered = responses
    .map((r, i) => `${i + 1}. ${r.answer}`)
    .join("\n");

  const raw = await haiku(
    CLUSTER_SYSTEM,
    `Question: ${question}\nRequired category: ${cat}\nCategory rule: ${categoryBrief(cat)}\n\nAnswers:\n${numbered}`,
    1800
  );

  const clean = raw.replace(/```json|```/g, "").trim();
  const start = clean.indexOf("[");
  const end = clean.lastIndexOf("]");
  if (start === -1 || end === -1) return [];

  let parsed: any[];
  try {
    parsed = JSON.parse(clean.slice(start, end + 1));
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];

  // Validate and de-duplicate membership — the model occasionally repeats or
  // drops an index, and a board with a double-counted answer is a wrong board.
  const seen = new Set<number>();
  const clusters: Cluster[] = [];

  for (const c of parsed) {
    const label = String(c?.label || "").trim().toUpperCase().slice(0, 40);
    const rationale = String(c?.rationale || "")
      .trim()
      .replace(/\s+/g, " ")
      .slice(0, 180);
    const membersRaw = Array.isArray(c?.members) ? c.members : [];
    const members: number[] = [];
    for (const m of membersRaw) {
      const n = Number(m);
      if (!Number.isInteger(n)) continue;
      if (n < 1 || n > responses.length) continue;
      if (seen.has(n)) continue;
      seen.add(n);
      members.push(n);
    }
    if (label && members.length > 0 && labelLooksOnCategory(label, cat)) {
      clusters.push({ label, rationale, members });
    }
  }

  // On-category orphans the model dropped → their own cluster.
  // Off-category orphans are discarded (they used to pollute emoji/food boards).
  for (let i = 1; i <= responses.length; i++) {
    if (seen.has(i)) continue;
    const answer = responses[i - 1].answer;
    const label = answer.toUpperCase().slice(0, 40);
    if (!labelLooksOnCategory(label, cat)) continue;
    clusters.push({
      label,
      rationale: "A lone larva took this swing — rare enough to spotlight.",
      members: [i],
    });
  }

  return clusters;
}

/** Soft lexical gate so obviously wrong labels never hit the board. */
function labelLooksOnCategory(label: string, cat: AnswerCategory): boolean {
  const n = normalize(label);
  if (!n) return false;

  const governanceJunk =
    /\b(roadmap|tokenomics|audit|receipt|governance|vault|staking|kpi|protocol|sybil|treasury)\b/;
  if (cat === "emoji") {
    // Emoji names are short; reject rants and governance phrases.
    if (n.split(" ").length > 3) return false;
    if (governanceJunk.test(n)) return false;
    return true;
  }
  if (cat === "food" && governanceJunk.test(n)) return false;
  if (cat === "animal" && governanceJunk.test(n)) return false;
  if (cat === "toy" && /\b(ponzi|pyramid|scheme)\b/.test(n)) return false;
  if ((cat === "movie" || cat === "tv" || cat === "song" || cat === "game") && governanceJunk.test(n)) {
    return false;
  }
  return true;
}

/** Collapse adjective / state variants the model left as separate rows. */
function mergeNearDuplicateClusters(clusters: Cluster[]): Cluster[] {
  const out: Cluster[] = [];
  for (const c of clusters) {
    const hit = out.find((o) => sameAnswerFamily(o.label, c.label));
    if (!hit) {
      out.push({ ...c, members: [...c.members] });
      continue;
    }
    hit.members.push(...c.members);
    if (c.label.replace(/\s+/g, "").length < hit.label.replace(/\s+/g, "").length) {
      hit.label = c.label;
    }
    if ((c.rationale?.length || 0) > (hit.rationale?.length || 0)) {
      hit.rationale = c.rationale;
    }
  }
  return out;
}

// ─── Board building ────────────────────────────────────────────────

const RESPONDENT_COUNT = 100;

/**
 * Build one complete board: survey N larvae, cluster their answers, rank them.
 * Costs roughly N + 1 Haiku calls.
 */
export async function buildBoard(questionId: string): Promise<SurveyBoard | null> {
  const q = await getQuestion(questionId);
  if (!q) return null;

  const index = await getIndex();
  const respondents = pickRespondents(index, questionId, RESPONDENT_COUNT);
  if (respondents.length === 0) return null;

  const surveyed = await mapWithConcurrency(respondents, 8, (r) =>
    surveyOne(r.wallet, q.text)
  );
  const responses = surveyed.filter(Boolean) as SurveyResponse[];
  if (responses.length < 3) return null;

  const cat = inferAnswerCategory(q.text);
  let clustered = await clusterResponses(q.text, responses);
  if (clustered.length === 0) return null;
  let clusters = mergeNearDuplicateClusters(clustered).filter((c) =>
    labelLooksOnCategory(c.label, cat)
  );

  // Quality gate: emoji/food/etc boards with <3 on-category rows are unplayable.
  if (clusters.length < 3) {
    console.error("survey board quality fail", questionId, cat, clusters.length);
    return null;
  }

  const ranked = clusters
    .sort((a, b) => b.members.length - a.members.length)
    .slice(0, MAX_BOARD_ANSWERS);

  const covered = ranked.reduce((n, c) => n + c.members.length, 0);
  // If clustering threw away almost everyone, the board is noise — refuse it.
  if (covered < Math.max(8, Math.floor(responses.length * 0.25))) {
    console.error("survey board coverage fail", questionId, covered, responses.length);
    return null;
  }

  const answers: BoardAnswer[] = ranked.map((c, i) => {
    const members = c.members.map((n) => responses[n - 1]).filter(Boolean);
    const sample = members[0]?.answer || c.label;
    const label = plainLabel(c.label) || c.label;
    const rawRationale = (c.rationale || "").trim();
    const rationale = isTemplateRationale(rawRationale, label, sample)
      ? fallbackRationale({ count: members.length, label })
      : rawRationale;
    return {
      rank: i + 1,
      label,
      count: members.length,
      points: members.length,
      voices: members.map((m) => m.name),
      sample,
      rationale,
      quotes: pickQuotes(members, label),
    };
  });

  return {
    id: q.id,
    question: q.text,
    answers,
    respondents: responses.length,
    totalPoints: answers.reduce((sum, a) => sum + a.points, 0),
    builtAt: new Date().toISOString(),
  };
}

// ─── Guess matching ────────────────────────────────────────────────

function normalize(s: string): string {
  return s
    .toLowerCase()
    // Apostrophes glue ("don't" → "dont"), other junk becomes spaces.
    .replace(/[''`´]/g, "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const MATCH_STOPWORDS = new Set([
  "a", "an", "the", "of", "for", "to", "in", "on", "with", "and", "or",
  "that", "this", "it", "is", "are", "be", "no", "not", "any", "some",
  "something", "someone", "thing", "things",
]);

function contentWords(s: string): string[] {
  return normalize(s)
    .split(" ")
    .filter((w) => w.length > 2 && !MATCH_STOPWORDS.has(w));
}

/** Free tier: exact, substring, or strong content-word overlap. */
function localMatch(guess: string, answers: BoardAnswer[]): BoardAnswer | null {
  const expanded = expandEmojiGuess(guess);
  for (const candidate of expanded) {
    const hit = localMatchOne(candidate, answers);
    if (hit) return hit;
  }
  return null;
}

/** Map a few common emoji characters to names players can type. */
function expandEmojiGuess(guess: string): string[] {
  const raw = guess.trim();
  if (!raw) return [];
  const out = [raw];
  const map: Record<string, string> = {
    "🚀": "rocket",
    "🔥": "fire",
    "🤡": "clown",
    "💀": "skull",
    "🐢": "turtle",
    "🤝": "handshake",
    "❤️": "heart",
    "♥️": "heart",
    "🦞": "lobster",
    "👀": "eyes",
    "💯": "hundred",
    "😭": "sob",
    "😂": "joy",
  };
  for (const [emoji, name] of Object.entries(map)) {
    if (raw.includes(emoji)) out.push(name);
  }
  return out;
}

function localMatchOne(guess: string, answers: BoardAnswer[]): BoardAnswer | null {
  const g = normalize(guess);
  if (!g) return null;
  const gWords = contentWords(guess);

  for (const a of answers) {
    const candidates = [a.label, a.sample];
    for (const c of candidates) {
      const n = normalize(c);
      if (!n) continue;
      if (n === g) return a;
      if (n.length > 4 && g.length > 4 && (n.includes(g) || g.includes(n))) {
        return a;
      }
    }
  }

  // Content-word overlap: every meaningful word in the shorter phrase appears
  // in the longer one. Catches "no roadmap" vs "vague roadmaps".
  if (gWords.length > 0) {
    for (const a of answers) {
      for (const c of [a.label, a.sample]) {
        const cWords = contentWords(c);
        if (cWords.length === 0) continue;
        const [short, long] =
          gWords.length <= cWords.length ? [gWords, cWords] : [cWords, gWords];
        const hits = short.filter((w) =>
          long.some((l) => l === w || l.startsWith(w) || w.startsWith(l))
        );
        if (hits.length === short.length && short.length > 0) return a;
      }
    }
  }

  return null;
}

const MATCH_SYSTEM = `You judge whether a player's guess means the same thing as any answer on a survey board.

You will receive the question, the player's guess, and a numbered list of unrevealed answers. Decide whether the guess means substantially the same thing as one of them.

Be reasonably generous about wording — "no timeline" and "VAGUE ROADMAPS" are a match; "🚀" and "ROCKET" are a match; "Don't Stop Believin'" and "DON'T STOP BELIEVIN" are a match.
Be strict about meaning — "bad code" and "VAGUE ROADMAPS" are not.

Respond with ONLY a JSON object, no markdown, no preamble:
{"match": 3}   — the number of the matching answer
{"match": null} — no answer means the same thing`;

/**
 * Check a guess against the unrevealed answers.
 * Tries the free local pass first; only calls Haiku when that misses.
 * Returns the matched answer, or null for a strike.
 */
export async function matchGuess(
  question: string,
  guess: string,
  unrevealed: BoardAnswer[]
): Promise<BoardAnswer | null> {
  if (!guess.trim() || unrevealed.length === 0) return null;

  const local = localMatch(guess, unrevealed);
  if (local) return local;

  // Global daily cap so a shared link can't drain the API key.
  const day = new Date().toISOString().slice(0, 10);
  const used = await redis.incr(MATCH_COUNT_KEY(day));
  if (used === 1) await redis.expire(MATCH_COUNT_KEY(day), 60 * 60 * 26);
  if (used > 500) return null; // fall back to strike rather than erroring out

  const numbered = unrevealed
    .map((a, i) => `${i + 1}. ${a.label} (also phrased as: ${a.sample})`)
    .join("\n");

  try {
    const raw = await haiku(
      MATCH_SYSTEM,
      `Question: ${question}\nPlayer's guess: "${guess.trim().slice(0, 80)}"\n\nUnrevealed answers:\n${numbered}`,
      200
    );
    const clean = raw.replace(/```json|```/g, "").trim();
    const start = clean.indexOf("{");
    const end = clean.lastIndexOf("}");
    if (start === -1 || end === -1) return null;
    const parsed = JSON.parse(clean.slice(start, end + 1));
    const n = Number(parsed?.match);
    if (!Number.isInteger(n) || n < 1 || n > unrevealed.length) return null;
    return unrevealed[n - 1];
  } catch {
    return null;
  }
}
