// lib/larvae-survey.ts
//
// Larvae Survey Game — survey-board game built from real larva responses.
//
// Boards are PRE-GENERATED by the build route and cached in Redis, so gameplay
// is instant. Generating one board = N in-character responses (one Haiku call
// per larva, run with limited concurrency) + one clustering call that groups
// those responses into ranked board answers.
//
// Guess matching is two-tier: a free normalized/substring pass first, then a
// single Haiku call only when that misses. Obvious hits cost nothing.
//
// Imports only redis + haiku + getIndex + getProfile from lib/larvae.ts —
// nothing in the existing codebase is modified.

import { redis, haiku, getIndex, getProfile } from "@/lib/larvae";

// ─── Types ─────────────────────────────────────────────────────────

/** One clustered answer on the board. */
export type BoardAnswer = {
  rank: number; // 1 = most common
  label: string; // short board text, e.g. "VAGUE ROADMAPS"
  count: number; // how many larvae gave this answer
  points: number; // count, used directly as score
  /** Names of the larvae whose responses landed in this cluster. */
  voices: string[];
  /** One representative quote, for the reveal. */
  sample: string;
  /** One sentence on why the hive clustered here. */
  rationale: string;
};

/** A complete playable board. */
export type SurveyBoard = {
  id: string;
  question: string;
  answers: BoardAnswer[];
  respondents: number; // how many larvae were surveyed
  totalPoints: number;
  builtAt: string;
};

/** Raw survey response before clustering. */
type SurveyResponse = {
  wallet: string;
  name: string;
  answer: string;
};

// ─── Question set ──────────────────────────────────────────────────
//
// Seed list is the starting bank. Runtime questions live in Redis so minting
// can grow the pool without a deploy. Build always reads the bank.

export type SurveyQuestion = {
  id: string;
  text: string;
  source: "seed" | "minted";
  createdAt: string;
};

export const SURVEY_QUESTIONS: { id: string; text: string }[] = [
  // All creative / personality bait — analogies, vibes, pop culture.
  // Avoid dry "utility" prompts where every larva says audit/roadmap.
  { id: "q01", text: "If CLAWD's story was a popular movie, which movie would it be?" },
  { id: "q02", text: "Name the animal a larva would reincarnate as." },
  { id: "q03", text: "Name a TV show that describes the hive's group chat." },
  { id: "q04", text: "Name the karaoke song the hive always ruins." },
  { id: "q05", text: "Name a board game that feels like shipping on-chain." },
  { id: "q06", text: "Name the sitcom character that would thrive in the hive." },
  { id: "q07", text: "Name something a larva would put on a dating profile." },
  { id: "q08", text: "Name the emoji that starts a fight in the hive." },
  { id: "q09", text: "Name a childhood toy that explains crypto culture." },
  { id: "q10", text: "Name the food that best describes governance drama." },
  { id: "q11", text: "Name a superhero a larva secretly thinks it is." },
  { id: "q12", text: "Name something you'd hear in a larva's nightmare." },
  { id: "q13", text: "If the hive was a reality show, which show would it be?" },
  { id: "q14", text: "Name the snack a larva rage-buys after a bad proposal." },
  { id: "q15", text: "Name a Disney villain that belongs in Discord moderation." },
  { id: "q16", text: "Name the Olympic sport that feels like waiting for a mint." },
  { id: "q17", text: "Name a fashion accessory a larva would never take off." },
  { id: "q18", text: "Name the conspiracy theory larvae whisper at 3am." },
  { id: "q19", text: "Name a video game boss that feels like a token unlock." },
  { id: "q20", text: "Name the houseplant that matches hive politics." },
  { id: "q21", text: "Name a weather forecast for the hive's mood this week." },
  { id: "q22", text: "Name the fictional job title a larva puts on LinkedIn." },
  { id: "q23", text: "Name a magic spell that would fix every roadmap." },
  { id: "q24", text: "Name the last thing a larva would say before rage-quitting." },
];

/** Soft cap so weekly minting doesn't grow forever. */
export const MAX_SURVEY_QUESTIONS = 60;

const QUESTIONS_KEY = "lpp:survey:questions";
const MAX_BOARD_ANSWERS = 8;
/** Ideal playable pool (3 main + 5 Swarm Rush). Auto-brew fills toward this. */
export const TARGET_BOARD_COUNT = 8;

function seedAsQuestions(): SurveyQuestion[] {
  const stamp = "2026-01-01";
  return SURVEY_QUESTIONS.map((q) => ({
    id: q.id,
    text: q.text,
    source: "seed" as const,
    createdAt: stamp,
  }));
}

async function loadQuestionBankRaw(): Promise<SurveyQuestion[]> {
  const raw = await redis.get<string | SurveyQuestion[]>(QUESTIONS_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

async function saveQuestionBank(questions: SurveyQuestion[]) {
  await redis.set(QUESTIONS_KEY, JSON.stringify(questions));
}

/** Wipe Redis questions and reseed from SURVEY_QUESTIONS (drops minted too). */
export async function resetQuestionBankFromSeed(): Promise<SurveyQuestion[]> {
  await redis.del(QUESTIONS_KEY);
  const seeded = seedAsQuestions();
  await saveQuestionBank(seeded);
  return seeded;
}

/**
 * Ensure Redis has at least the seed questions. Safe to call often.
 * New seed entries added in code are merged in on the next call.
 */
export async function ensureQuestionBank(): Promise<SurveyQuestion[]> {
  const bank = await loadQuestionBankRaw();
  const byId = new Map(bank.map((q) => [q.id, q]));
  let changed = bank.length === 0;

  for (const s of seedAsQuestions()) {
    if (!byId.has(s.id)) {
      byId.set(s.id, s);
      changed = true;
    }
  }

  const merged = Array.from(byId.values()).sort((a, b) => a.id.localeCompare(b.id));
  if (changed) await saveQuestionBank(merged);
  return merged;
}

export async function getQuestionBank(): Promise<SurveyQuestion[]> {
  return ensureQuestionBank();
}

export async function getQuestion(id: string): Promise<SurveyQuestion | null> {
  const bank = await getQuestionBank();
  return bank.find((q) => q.id === id) || null;
}

function nextQuestionIds(bank: SurveyQuestion[], count: number): string[] {
  let max = 0;
  for (const q of bank) {
    const m = /^q(\d+)$/i.exec(q.id);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  const ids: string[] = [];
  for (let i = 1; i <= count; i++) {
    ids.push(`q${String(max + i).padStart(2, "0")}`);
  }
  return ids;
}

function normQuestion(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tooSimilar(a: string, b: string): boolean {
  const wa = new Set(normQuestion(a).split(" ").filter((w) => w.length > 2));
  const wb = new Set(normQuestion(b).split(" ").filter((w) => w.length > 2));
  if (wa.size === 0 || wb.size === 0) return normQuestion(a) === normQuestion(b);
  let overlap = 0;
  for (const w of wa) if (wb.has(w)) overlap++;
  const ratio = overlap / Math.min(wa.size, wb.size);
  return ratio >= 0.7 || normQuestion(a) === normQuestion(b);
}

const MINT_SYSTEM = `You invent survey questions for a knockoff game-show survey about larvae — personal AI agents in the CLAWD / crypto-build hive.

Goal: questions that different larvae will answer DIFFERENTLY, with personality — not dry "utility" prompts where everyone says audit / roadmap / transparency.

Prefer creative formats:
- Analogies: "If CLAWD's story was a movie, which movie…", "Name the animal a larva would reincarnate as."
- Pop culture / vibes: TV shows, songs, board games, sitcom characters, emojis, food metaphors, nightmares, dating-profile bits.
- Social / hive drama that still invites weird answers.

Avoid:
- Generic governance checklists (audits, roadmaps, KPIs) as the obvious only answer.
- Near-duplicates of the existing list.
- Yes/no or one-correct-answer trivia.

Rules:
- One sentence each, under 110 characters.
- May start with Name / If / What / Which / Who.
- Return ONLY a JSON array of strings, no markdown, no preamble.
Example: ["If the hive was a reality show, which show would it be?","Name the snack a larva rage-buys after a bad proposal."]`;

/**
 * Mint up to `count` new questions into the Redis bank.
 * Dedupes against the existing bank. No-ops if already at MAX_SURVEY_QUESTIONS.
 */
export async function mintQuestions(count = 3): Promise<{
  minted: SurveyQuestion[];
  bankSize: number;
  skippedReason?: string;
}> {
  const bank = await getQuestionBank();
  const room = MAX_SURVEY_QUESTIONS - bank.length;
  if (room <= 0) {
    return { minted: [], bankSize: bank.length, skippedReason: "at cap" };
  }
  const want = Math.min(count, room);

  const existingList = bank.map((q) => `- ${q.text}`).join("\n");
  const raw = await haiku(
    MINT_SYSTEM,
    `Existing questions (do not duplicate):\n${existingList}\n\nInvent ${want} NEW questions.`,
    500
  );

  let parsed: unknown;
  try {
    const clean = raw.replace(/```json|```/g, "").trim();
    const start = clean.indexOf("[");
    const end = clean.lastIndexOf("]");
    parsed = JSON.parse(clean.slice(start, end + 1));
  } catch {
    return { minted: [], bankSize: bank.length, skippedReason: "parse failed" };
  }

  if (!Array.isArray(parsed)) {
    return { minted: [], bankSize: bank.length, skippedReason: "not an array" };
  }

  const candidates = parsed
    .map((t) => String(t || "").trim())
    .filter((t) => t.length >= 12 && t.length <= 140)
    .filter((t) => /^(name|if |what |which |who |where )/i.test(t));

  const accepted: string[] = [];
  for (const text of candidates) {
    if (accepted.length >= want) break;
    const clash =
      bank.some((q) => tooSimilar(q.text, text)) ||
      accepted.some((a) => tooSimilar(a, text));
    if (!clash) {
      accepted.push(text.replace(/\s+/g, " ").trim());
    }
  }

  if (accepted.length === 0) {
    return { minted: [], bankSize: bank.length, skippedReason: "all duplicates" };
  }

  const ids = nextQuestionIds(bank, accepted.length);
  const minted: SurveyQuestion[] = accepted.map((text, i) => ({
    id: ids[i],
    text,
    source: "minted" as const,
    createdAt: new Date().toISOString().slice(0, 10),
  }));

  const next = [...bank, ...minted].sort((a, b) => a.id.localeCompare(b.id));
  await saveQuestionBank(next);
  return { minted, bankSize: next.length };
}

// ─── Redis keys ────────────────────────────────────────────────────

const BOARD_KEY = (id: string) => `lpp:survey:board:${id}`;
const BOARD_INDEX_KEY = "lpp:survey:index";
const BUILD_QUEUE_KEY = "lpp:survey:queue";
const MATCH_COUNT_KEY = (day: string) => `lpp:survey:matches:${day}`;

// ─── Redis ops ─────────────────────────────────────────────────────

export async function saveBoard(board: SurveyBoard) {
  await redis.set(BOARD_KEY(board.id), JSON.stringify(board));
  const index = await getBoardIndex();
  if (!index.includes(board.id)) {
    await redis.set(BOARD_INDEX_KEY, JSON.stringify([...index, board.id]));
  }
}

/** Decorative fluff + state modifiers models bolt onto the same answer. */
const LABEL_ARTICLES = new Set(["a", "an", "the", "my", "our", "some", "any"]);
const LABEL_DECORATIVE = new Set([
  "fierce", "chaotic", "crazy", "wild", "sassy", "spicy", "cursed", "based",
  "epic", "legendary", "ultimate", "absolute", "total", "giant", "tiny",
  "little", "big", "angry", "sleepy", "feral", "deranged", "holy", "lowkey",
  "literally", "basically", "probably", "definitely", "obviously", "kinda",
  "super", "mega", "ultra", "random", "weird", "goofy", "silly", "smug",
  // state / quality padding that creates fake duplicate board rows
  "overcooked", "undercooked", "uncooked", "overripe", "underripe", "raw",
  "burnt", "burned", "cold", "hot", "broken", "failed", "failing", "collapsing",
  "collapse", "collapsed", "decay", "decaying", "rotting", "rotten", "variant",
  "versions", "version", "style", "vibes", "energy", "core", "mode",
]);
const LABEL_FILLER = new Set([...LABEL_ARTICLES, ...LABEL_DECORATIVE]);

function foldText(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function contentTokens(label: string): string[] {
  return foldText(label)
    .split(" ")
    .filter((w) => w.length > 1 && !LABEL_FILLER.has(w));
}

function labelCore(label: string): string {
  return contentTokens(label).join(" ");
}

/** True when two board labels are the same idea with different padding. */
function sameAnswerFamily(a: string, b: string): boolean {
  const ta = contentTokens(a);
  const tb = contentTokens(b);
  if (ta.length === 0 || tb.length === 0) return false;
  const ca = ta.join(" ");
  const cb = tb.join(" ");
  if (ca === cb) return true;
  if (ca.includes(cb) || cb.includes(ca)) return true;
  const [short, long] = ta.length <= tb.length ? [ta, tb] : [tb, ta];
  if (short.every((t) => long.includes(t))) return true;
  // Shared distinctive noun (e.g. all the SOUFFLÉ / OVERCOOKED SOUFFLÉ rows)
  const nouns = (toks: string[]) => toks.filter((t) => t.length >= 4);
  const na = nouns(ta);
  const nb = nouns(tb);
  return na.some((n) => nb.includes(n));
}

/** Board label: drop decorative/state fluff, keep the plain noun/title. */
function plainLabel(label: string): string {
  const folded = foldText(label);
  const words = folded.split(" ").filter(Boolean);
  const kept = words.filter((w) => !LABEL_DECORATIVE.has(w));
  return (kept.length > 0 ? kept : words).join(" ").toUpperCase().slice(0, 40);
}

function fallbackRationale(a: { count: number; sample?: string; label: string }): string {
  return `${a.count} larva${a.count === 1 ? "" : "e"} landed here — e.g. "${(a.sample || a.label).slice(0, 80)}".`;
}

/**
 * Fix already-cached boards without a rebuild: strip decorative adjectives,
 * merge near-duplicate rows, backfill rationale.
 */
function sanitizeBoard(board: SurveyBoard): { board: SurveyBoard; changed: boolean } {
  const raw = board.answers || [];
  const merged: BoardAnswer[] = [];

  for (const a of raw) {
    const label = plainLabel(a.label || "");
    if (!label) continue;
    const next: BoardAnswer = {
      rank: a.rank,
      label,
      count: a.count,
      points: a.points ?? a.count,
      voices: [...(a.voices || [])],
      sample: a.sample || label,
      rationale: (a.rationale || "").trim() || fallbackRationale(a),
    };
    const hit = merged.find((o) => sameAnswerFamily(o.label, next.label));
    if (!hit) {
      merged.push(next);
      continue;
    }
    hit.count += next.count;
    hit.points += next.points;
    hit.voices.push(...next.voices);
    // Prefer the shortest plain label (SOUFFLÉ beats OVERCOOKED SOUFFLÉ)
    if (next.label.replace(/\s+/g, "").length < hit.label.replace(/\s+/g, "").length) {
      hit.label = next.label;
    }
    if (!hit.sample || next.sample.length < hit.sample.length) hit.sample = next.sample;
    if (next.rationale.length > hit.rationale.length) hit.rationale = next.rationale;
  }

  const ranked = merged
    .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label))
    .slice(0, MAX_BOARD_ANSWERS)
    .map((a, i) => ({ ...a, rank: i + 1, points: a.count }));

  const totalPoints = ranked.reduce((s, a) => s + a.points, 0);
  const changed =
    ranked.length !== raw.length ||
    totalPoints !== board.totalPoints ||
    ranked.some((a, i) => {
      const b = raw[i];
      return (
        !b ||
        a.label !== plainLabel(b.label || "") ||
        a.count !== b.count ||
        !(b.rationale || "").trim()
      );
    });

  return {
    board: { ...board, answers: ranked, totalPoints },
    changed,
  };
}

export async function getBoard(id: string): Promise<SurveyBoard | null> {
  const raw = await redis.get<string | SurveyBoard>(BOARD_KEY(id));
  if (!raw) return null;
  const board: SurveyBoard = typeof raw === "string" ? JSON.parse(raw) : raw;
  const { board: cleaned, changed } = sanitizeBoard(board);
  if (changed) {
    // Persist cleaned labels / merged dupes so players never need a manual rebuild.
    await saveBoard(cleaned);
  }
  return cleaned;
}

export async function getBoardIndex(): Promise<string[]> {
  const raw = await redis.get<string | string[]>(BOARD_INDEX_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export async function getAllBoards(): Promise<SurveyBoard[]> {
  const index = await getBoardIndex();
  const boards = await Promise.all(index.map((id) => getBoard(id)));
  return boards.filter(Boolean) as SurveyBoard[];
}

export async function getBuildQueue(): Promise<string[]> {
  const raw = await redis.get<string | string[]>(BUILD_QUEUE_KEY);
  if (!raw) return [];
  return typeof raw === "string" ? JSON.parse(raw) : raw;
}

export async function setBuildQueue(ids: string[]) {
  await redis.set(BUILD_QUEUE_KEY, JSON.stringify(ids));
}

export async function clearBuildQueue() {
  await redis.del(BUILD_QUEUE_KEY);
}

export async function clearAllBoards() {
  const index = await getBoardIndex();
  for (const id of index) await redis.del(BOARD_KEY(id));
  await redis.del(BOARD_INDEX_KEY);
  await redis.del(BUILD_QUEUE_KEY);
}

const ENSURE_LOCK_KEY = "lpp:survey:ensure-lock";

/**
 * Public-safe progress tick: build missing boards toward TARGET_BOARD_COUNT.
 * No wipe, no secret. Rate-limited so page polls can't stampede Redis/LLM.
 * Safe to call from the play page — advances one chunk per call.
 */
export async function tickMissingBoardBuild(
  budgetMs = 45_000
): Promise<{
  builtThisRun: { id: string; answers: number; respondents: number }[];
  remaining: number;
  brewing: boolean;
  skipped?: string;
}> {
  const lock = await redis.set(ENSURE_LOCK_KEY, "1", { nx: true, ex: 90 });
  if (lock !== "OK") {
    const existing = await getBoardIndex();
    const queue = await getBuildQueue();
    return {
      builtThisRun: [],
      remaining: queue.length,
      brewing: existing.length < TARGET_BOARD_COUNT || queue.length > 0,
      skipped: "busy",
    };
  }

  try {
    await ensureQuestionBank();
    const start = Date.now();
    let queue = await getBuildQueue();
    const existing = await getBoardIndex();
    const bank = await getQuestionBank();

    if (queue.length === 0) {
      const missing = bank
        .filter((q) => !existing.includes(q.id))
        .map((q) => q.id)
        .slice(0, Math.max(0, TARGET_BOARD_COUNT - existing.length));
      if (missing.length === 0) {
        return {
          builtThisRun: [],
          remaining: 0,
          brewing: false,
          skipped: "full",
        };
      }
      queue = missing;
      await setBuildQueue(queue);
    }

    const builtThisRun: { id: string; answers: number; respondents: number }[] = [];

    while (queue.length > 0 && Date.now() - start < budgetMs) {
      const id = queue.shift()!;
      try {
        const board = await buildBoard(id);
        if (board) {
          await saveBoard(board);
          builtThisRun.push({
            id: board.id,
            answers: board.answers.length,
            respondents: board.respondents,
          });
        }
      } catch {
        // leave failed id out of queue — don't spin forever
      }
      await setBuildQueue(queue);
      // One board per tick is enough for public ensure; keep latency predictable.
      if (builtThisRun.length >= 1) break;
    }

    if (queue.length === 0) await clearBuildQueue();
    const finalIndex = await getBoardIndex();
    return {
      builtThisRun,
      remaining: queue.length,
      brewing: finalIndex.length < TARGET_BOARD_COUNT || queue.length > 0,
    };
  } finally {
    await redis.del(ENSURE_LOCK_KEY);
  }
}

// ─── Respondent selection ──────────────────────────────────────────

/**
 * Pick which larvae answer a given question.
 *
 * Deliberately NOT "top N by response count" — that makes every board the same
 * five voices. Instead: seed a rotating window from the question id so each
 * question surveys a different slice of the hive, while staying deterministic
 * (rebuilding the same board twice gives the same respondents).
 */
function pickRespondents(
  index: { wallet: string; responseCount: number }[],
  questionId: string,
  count: number
): { wallet: string }[] {
  if (index.length === 0) return [];

  // Only consider larvae with enough history to have a real personality.
  const eligible = index.filter((e) => e.responseCount >= 3);
  const pool = eligible.length >= count ? eligible : index;

  let seed = 0;
  for (const c of questionId) seed = (seed * 31 + c.charCodeAt(0)) >>> 0;

  const start = seed % pool.length;
  const picked: { wallet: string }[] = [];
  const stride = 1 + (seed % 3); // vary the stride so windows overlap differently

  for (let i = 0; i < Math.min(count, pool.length); i++) {
    const idx = (start + i * stride) % pool.length;
    const entry = pool[idx];
    if (!picked.some((p) => p.wallet === entry.wallet)) {
      picked.push({ wallet: entry.wallet });
    }
  }

  // Stride may collide on small pools — top up sequentially if short.
  if (picked.length < Math.min(count, pool.length)) {
    for (const entry of pool) {
      if (picked.length >= count) break;
      if (!picked.some((p) => p.wallet === entry.wallet)) {
        picked.push({ wallet: entry.wallet });
      }
    }
  }

  return picked;
}

// ─── Survey phase ──────────────────────────────────────────────────

const SURVEY_SYSTEM = `You are a larva — a personal AI governance agent in the $CLAWD ecosystem — answering a survey question in character.

Answer with a SHORT phrase: usually 1-4 words (movie titles, animal names, song names, and proper nouns are fine). Not a sentence. Not an explanation. Just the answer itself.

Rules:
- Name the thing itself. Do NOT pad with state/adjective fluff ("overcooked soufflé", "fierce honey badger") — say "soufflé" / "honey badger".
- No filler like "definitely", "probably", "obviously", "lowkey", "collapse", "variant", "broken".
- Answer must actually fit the question category (toy → a real toy; food → a real food).

Good: "The Social Network" / "honey badger" / "soufflé" / "Tamagotchi"
Bad: "overcooked soufflé" / "soufflé collapse" / "fierce honey badger" / "ponzi pyramid scheme" (not a toy)

Answer from YOUR personality, not the obvious general answer. Unusual picks are fine — decorative wording is not.

Respond with ONLY the phrase, nothing else. No quotes, no punctuation at the end.`;

async function surveyOne(
  wallet: string,
  question: string
): Promise<SurveyResponse | null> {
  const p = await getProfile(wallet);
  if (!p) return null;

  const system = `${SURVEY_SYSTEM}

You are "${p.profile.name}".
Tone: ${p.profile.tone}
Values: ${p.profile.values.join("; ")}
Quirks: ${p.profile.quirks.join("; ")}
About you: ${p.profile.summary}`;

  try {
    const raw = await haiku(system, question, 40);
    const answer = raw
      .trim()
      .replace(/^["'`]+|["'`.,!]+$/g, "")
      .replace(/\s+/g, " ")
      .slice(0, 60);
    if (!answer) return null;
    // Drop decorative adjectives ("fierce honey badger" → "honey badger").
    const words = answer.split(/\s+/);
    const kept = words.filter((w) => !LABEL_DECORATIVE.has(w.toLowerCase()));
    const cleaned = (kept.length > 0 ? kept : words).join(" ").slice(0, 60);
    return { wallet: p.wallet, name: p.profile.name, answer: cleaned };
  } catch {
    return null;
  }
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let i = 0;
  async function worker() {
    while (i < items.length) {
      const idx = i++;
      results[idx] = await fn(items[idx]);
    }
  }
  await Promise.all(new Array(Math.min(limit, items.length)).fill(0).map(worker));
  return results;
}

// ─── Clustering phase ──────────────────────────────────────────────

const CLUSTER_SYSTEM = `You are building a survey board for a "guess the top answers" style survey game.

You will receive a question and a numbered list of short answers from different respondents. Group answers that mean the SAME THING into clusters, even when worded differently.

CRITICAL — do NOT leave state/adjective variants as separate rows. These are ONE cluster each:
- "soufflé" + "overcooked soufflé" + "undercooked soufflé" + "soufflé collapse" + "uncooked soufflé" → SOUFFLÉ
- "overripe fruit salad" + "overripe fruit decay" → OVERRIPE FRUIT
- "honey badger" + "fierce honey badger" → HONEY BADGER
- "lego with no instructions" + "lego mindstorms" → LEGO (same toy family when the question is about toys)

Rules:
- Merge aggressively on meaning and on shared head noun.
- Never invent adjectives. Prefer the PLAINEST shared noun/phrase for the label (1-3 words, UPPERCASE).
- For each cluster, write a "rationale": exactly ONE sentence grounded in what they said.
- Return clusters sorted by size, largest first.
- Include every respondent number exactly once, in exactly one cluster.
- Answers that are NOT what the question asked for (e.g. "ponzi scheme" for a childhood-toy question) may stay as their own row — do not invent toys for them.

Respond with ONLY a JSON array, no markdown, no preamble:
[{"label":"SOUFFLÉ","rationale":"The hive kept describing governance as a soufflé that falls the second you look at it.","members":[1,4,9]}, ...]`;

type Cluster = { label: string; rationale: string; members: number[] };

async function clusterResponses(
  question: string,
  responses: SurveyResponse[]
): Promise<Cluster[]> {
  const numbered = responses
    .map((r, i) => `${i + 1}. ${r.answer}`)
    .join("\n");

  const raw = await haiku(
    CLUSTER_SYSTEM,
    `Question: ${question}\n\nAnswers:\n${numbered}`,
    1800
  );

  const clean = raw.replace(/```json|```/g, "").trim();
  const start = clean.indexOf("[");
  const end = clean.lastIndexOf("]");
  if (start === -1 || end === -1) return [];

  let parsed: any[];
  try {
    parsed = JSON.parse(clean.slice(start, end + 1));
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];

  // Validate and de-duplicate membership — the model occasionally repeats or
  // drops an index, and a board with a double-counted answer is a wrong board.
  const seen = new Set<number>();
  const clusters: Cluster[] = [];

  for (const c of parsed) {
    const label = String(c?.label || "").trim().toUpperCase().slice(0, 40);
    const rationale = String(c?.rationale || "")
      .trim()
      .replace(/\s+/g, " ")
      .slice(0, 180);
    const membersRaw = Array.isArray(c?.members) ? c.members : [];
    const members: number[] = [];
    for (const m of membersRaw) {
      const n = Number(m);
      if (!Number.isInteger(n)) continue;
      if (n < 1 || n > responses.length) continue;
      if (seen.has(n)) continue;
      seen.add(n);
      members.push(n);
    }
    if (label && members.length > 0) clusters.push({ label, rationale, members });
  }

  // Any respondent the model dropped becomes its own cluster, so counts still
  // add up to the number surveyed.
  for (let i = 1; i <= responses.length; i++) {
    if (!seen.has(i)) {
      const answer = responses[i - 1].answer;
      clusters.push({
        label: answer.toUpperCase().slice(0, 40),
        rationale: `One larva put it plainly: "${answer.slice(0, 80)}".`,
        members: [i],
      });
    }
  }

  return clusters;
}

/** Collapse adjective / state variants the model left as separate rows. */
function mergeNearDuplicateClusters(clusters: Cluster[]): Cluster[] {
  const out: Cluster[] = [];
  for (const c of clusters) {
    const hit = out.find((o) => sameAnswerFamily(o.label, c.label));
    if (!hit) {
      out.push({ ...c, members: [...c.members] });
      continue;
    }
    hit.members.push(...c.members);
    if (c.label.replace(/\s+/g, "").length < hit.label.replace(/\s+/g, "").length) {
      hit.label = c.label;
    }
    if ((c.rationale?.length || 0) > (hit.rationale?.length || 0)) {
      hit.rationale = c.rationale;
    }
  }
  return out;
}

// ─── Board building ────────────────────────────────────────────────

const RESPONDENT_COUNT = 100;

/**
 * Build one complete board: survey N larvae, cluster their answers, rank them.
 * Costs roughly N + 1 Haiku calls.
 */
export async function buildBoard(questionId: string): Promise<SurveyBoard | null> {
  const q = await getQuestion(questionId);
  if (!q) return null;

  const index = await getIndex();
  const respondents = pickRespondents(index, questionId, RESPONDENT_COUNT);
  if (respondents.length === 0) return null;

  const surveyed = await mapWithConcurrency(respondents, 8, (r) =>
    surveyOne(r.wallet, q.text)
  );
  const responses = surveyed.filter(Boolean) as SurveyResponse[];
  if (responses.length < 3) return null;

  const clustered = await clusterResponses(q.text, responses);
  if (clustered.length === 0) return null;
  const clusters = mergeNearDuplicateClusters(clustered);

  const ranked = clusters
    .sort((a, b) => b.members.length - a.members.length)
    .slice(0, MAX_BOARD_ANSWERS);

  const answers: BoardAnswer[] = ranked.map((c, i) => {
    const members = c.members.map((n) => responses[n - 1]).filter(Boolean);
    const sample = members[0]?.answer || c.label;
    const rationale =
      c.rationale ||
      `${members.length} larva${members.length === 1 ? "" : "e"} landed here — e.g. "${sample.slice(0, 80)}".`;
    return {
      rank: i + 1,
      label: c.label,
      count: members.length,
      points: members.length,
      voices: members.map((m) => m.name),
      sample,
      rationale,
    };
  });

  return {
    id: q.id,
    question: q.text,
    answers,
    respondents: responses.length,
    totalPoints: answers.reduce((sum, a) => sum + a.points, 0),
    builtAt: new Date().toISOString(),
  };
}

// ─── Guess matching ────────────────────────────────────────────────

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const MATCH_STOPWORDS = new Set([
  "a", "an", "the", "of", "for", "to", "in", "on", "with", "and", "or",
  "that", "this", "it", "is", "are", "be", "no", "not", "any", "some",
  "something", "someone", "thing", "things",
]);

function contentWords(s: string): string[] {
  return normalize(s)
    .split(" ")
    .filter((w) => w.length > 2 && !MATCH_STOPWORDS.has(w));
}

/** Free tier: exact, substring, or strong content-word overlap. */
function localMatch(guess: string, answers: BoardAnswer[]): BoardAnswer | null {
  const g = normalize(guess);
  if (!g) return null;
  const gWords = contentWords(guess);

  for (const a of answers) {
    const candidates = [a.label, a.sample];
    for (const c of candidates) {
      const n = normalize(c);
      if (!n) continue;
      if (n === g) return a;
      if (n.length > 4 && g.length > 4 && (n.includes(g) || g.includes(n))) {
        return a;
      }
    }
  }

  // Content-word overlap: every meaningful word in the shorter phrase appears
  // in the longer one. Catches "no roadmap" vs "vague roadmaps".
  if (gWords.length > 0) {
    for (const a of answers) {
      for (const c of [a.label, a.sample]) {
        const cWords = contentWords(c);
        if (cWords.length === 0) continue;
        const [short, long] =
          gWords.length <= cWords.length ? [gWords, cWords] : [cWords, gWords];
        const hits = short.filter((w) =>
          long.some((l) => l === w || l.startsWith(w) || w.startsWith(l))
        );
        if (hits.length === short.length && short.length > 0) return a;
      }
    }
  }

  return null;
}

const MATCH_SYSTEM = `You judge whether a player's guess means the same thing as any answer on a survey board.

You will receive the question, the player's guess, and a numbered list of unrevealed answers. Decide whether the guess means substantially the same thing as one of them.

Be reasonably generous about wording — "no timeline" and "VAGUE ROADMAPS" are a match. Be strict about meaning — "bad code" and "VAGUE ROADMAPS" are not.

Respond with ONLY a JSON object, no markdown, no preamble:
{"match": 3}   — the number of the matching answer
{"match": null} — no answer means the same thing`;

/**
 * Check a guess against the unrevealed answers.
 * Tries the free local pass first; only calls Haiku when that misses.
 * Returns the matched answer, or null for a strike.
 */
export async function matchGuess(
  question: string,
  guess: string,
  unrevealed: BoardAnswer[]
): Promise<BoardAnswer | null> {
  if (!guess.trim() || unrevealed.length === 0) return null;

  const local = localMatch(guess, unrevealed);
  if (local) return local;

  // Global daily cap so a shared link can't drain the API key.
  const day = new Date().toISOString().slice(0, 10);
  const used = await redis.incr(MATCH_COUNT_KEY(day));
  if (used === 1) await redis.expire(MATCH_COUNT_KEY(day), 60 * 60 * 26);
  if (used > 500) return null; // fall back to strike rather than erroring out

  const numbered = unrevealed
    .map((a, i) => `${i + 1}. ${a.label} (also phrased as: ${a.sample})`)
    .join("\n");

  try {
    const raw = await haiku(
      MATCH_SYSTEM,
      `Question: ${question}\nPlayer's guess: "${guess.trim().slice(0, 80)}"\n\nUnrevealed answers:\n${numbered}`,
      60
    );
    const clean = raw.replace(/```json|```/g, "").trim();
    const start = clean.indexOf("{");
    const end = clean.lastIndexOf("}");
    if (start === -1 || end === -1) return null;
    const parsed = JSON.parse(clean.slice(start, end + 1));
    const n = Number(parsed?.match);
    if (!Number.isInteger(n) || n < 1 || n > unrevealed.length) return null;
    return unrevealed[n - 1];
  } catch {
    return null;
  }
}
